version: 2.1
jobs:
  build: /web
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run:
          name: build backend
          command: composer install
      